services:
  postgres:
    image: postgres:15
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: sh -c "npm install && npx prisma generate && npm run start:dev"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm start"

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
